### ISSUE TITLE
Can't login with rest api credentials

### ISSUE THREAD

**Issue by sidelux** [guizzo/hydra#2]
Hi,
i have installed and started your ui with the following commands:
```
set api.rest.username admin
set api.rest.password adminpsw
api.rest on
set http.server.address 127.0.0.1
set http.server.path /Users/Fenix/hydra/dist/hydra
 http.server on
```
But when i try to login it apprear Unknow error.

![image](https://user-images.githubusercontent.com/18572941/54292811-1aa31700-45af-11e9-8129-d1f53aa619a4.png)
![image](https://user-images.githubusercontent.com/18572941/54292853-30184100-45af-11e9-96f8-fe6519f834e1.png)

Maybe i miss the link between api url and hydra?
Thanks

**Comment by SymbianSyMoh** [comment]
Same problem here!

**Comment by duan78** [comment]
Same here; tried everything ...

**Comment by evilsocket** [comment]
THIS IS NOT STABLE YET FFS
